apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: mongo-app
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  #upar vali line tk deployment hogya
  #ab niche se pod ke bare me baat hogi
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: mongo-app
    spec:
      containers:
        - name: mongo-app
          # Run this image
          image: mongo:latest

---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: service-mongodb
spec:
  ports:
    # Accept traffic sent to port 8080
    - name: tcp
      port: 27017
      targetPort: 27017
  selector: #mtlab service konse pod ke liye use krna hai
    # Loadbalance traffic across Pods matching
    # this label selector
    app: mongo-app
