apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: node-app
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  #upar vali line tk deployment hogya
  #ab niche se pod ke bare me baat hogi
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: node-app
    spec:
      containers:
        - name: node-app
          # Run this image
          image: philippaul/node-mongo-db:04
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_PORT

---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: service-node-app
spec:
  ports:
    # Accept traffic sent to port 8080
    - name: http
      port: 8080
      targetPort: 3000
  selector: #mtlab service konse pod ke liye use krna hai
    # Loadbalance traffic across Pods matching
    # this label selector
    app: node-app
  type: LoadBalancer
